"""Regenerate `version_info.txt`, the Windows version resource PyInstaller embeds.

The resource has to carry the real version: it is what Windows shows in the
file properties, and a binary whose metadata says 0.1.0 while the app reports
1.2.3 looks exactly like the tampering heuristic antivirus scanners watch for.
Keeping it hand-edited guaranteed it would drift, so the release workflow
regenerates it before every build - see .github/workflows/build-installers.yml.

Usage:
    python packaging/make_version_info.py [VERSION]

With no argument the version comes from the installed package metadata, which
is the same source `rubit_mcp_mail.__version__` uses.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

OUTPUT = Path(__file__).with_name("version_info.txt")

TEMPLATE = """\
# PyInstaller Windows version resource. Ignored on other platforms.
#
# Gives both executables a real product name, description and version instead
# of no metadata at all - anonymous-looking binaries are more likely to be
# flagged by heuristic antivirus scanners. Not a substitute for code-signing,
# which is the durable fix and tracked separately.
#
# GENERATED by packaging/make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numeric},
    prodvers={numeric},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          "040904B0",
          [
            StringStruct("CompanyName", "rubit-mcp-mail"),
            StringStruct("FileDescription", "rubit-mcp-mail - read-only mail MCP server"),
            StringStruct("FileVersion", "{version}"),
            StringStruct("InternalName", "rubit-mcp-mail"),
            StringStruct("LegalCopyright", "rubit-mcp-mail contributors"),
            StringStruct("OriginalFilename", "rubit-mcp-mail"),
            StringStruct("ProductName", "rubit-mcp-mail"),
            StringStruct("ProductVersion", "{version}"),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct("Translation", [0, 1200])]),
  ],
)
"""


def numeric_version(version: str) -> tuple[int, int, int, int]:
    """The leading `major.minor.patch` of `version` as the 4-int tuple Windows wants.

    Windows version resources are four plain integers, so any prerelease or
    local suffix is dropped: `1.2.3-rc.4` becomes `(1, 2, 3, 0)`.
    """
    match = re.match(r"(\d+)(?:\.(\d+))?(?:\.(\d+))?", version)
    if match is None:
        raise SystemExit(f"cannot derive a numeric version from {version!r}")
    major, minor, patch = (int(part or 0) for part in match.groups())
    return (major, minor, patch, 0)


def main(argv: list[str]) -> int:
    if len(argv) > 1:
        version = argv[1]
    else:
        from importlib.metadata import version as installed_version

        version = installed_version("rubit-mcp-mail")

    OUTPUT.write_text(
        TEMPLATE.format(version=version, numeric=numeric_version(version)),
        encoding="utf-8",
    )
    print(f"{OUTPUT.name}: {version} {numeric_version(version)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
